# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LIUSU
email: susang945@163.com
description:  假装这里有个正儿八经的自我介绍
baseurl: "/myBlog" # the subpath of your site, e.g. /blog
url: "https://nicolasjackson.github.io/NicolasJackson/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
